### ISSUE TITLE
Support for x509 v1 certificates.[INFO-REQUEST]

### ISSUE THREAD

**Issue by amrx101** [briansmith/webpki#132]
Is there a specific reason that x509v1 certificates are not supported. When a server provides a v1 x509 certificate, a `BadDER` error occurs. Any specific reason(s) for not allowing v1 certificate.

**Comment by briansmith** [comment]
The Web PKI requires that the subjectAltName extension appear in the end-entity certificate indicating which DNS name(s) the certificate is valid for. The subjectAltName extension is only allowed in v3 certificates. There is an existing issue about improving the error reporting so that a clearer (than `BadDER`) error is returned when a certificate is rejected for this reason.
