### ISSUE TITLE
Version 0.22.0 is not pushed / tagged

### ISSUE THREAD

**Issue by robin-kunzler** [briansmith/webpki#243]
The latest rustls 0.20.0 now uses webpki 0.22.0 and this is also on [crates.io](https://crates.io/crates/webpki), but that version does not seem to exist in this repository. 

It would be great for us to have the code pushed here due to the following reasons: 
1. Since this is a security critical component, it is important that the diff to the previous version is public and can be reviewed. 
2. We would like to patch version 0.22.0 with [PR 241](https://github.com/briansmith/webpki/pull/241) until that PR is merged and released, but we cannot because the code is not public. 

Could you please push version 0.22.0 and tag the releases? This would be very much appreciated, thanks!

**Comment by randombit** [comment]
The revision https://github.com/briansmith/webpki/commit/0b7cbf2d327d7665d9d06072bf46b2e7ca05f065 seems to be 0.22 so possibly it's just that the tag was not pushed?

**Comment by fspreiss** [comment]
Is this indeed just a matter of a missing tag? If so, it would be great if the respective tag could be pushed. @briansmith, you are the author of [the commit in question](https://github.com/briansmith/webpki/commit/0b7cbf2d327d7665d9d06072bf46b2e7ca05f065), so it would be great if you could comment on this and/or push the tag.

As @robin-kunzler already pointed out, having the tag pushed is also important for projects such as [Rustls](https://github.com/rustls/rustls) that rely on `webpki` so that (security) code reviews can be performed and patches can be created (if necessary). Thanks!

**Comment by briansmith** [comment]
It's been my policy to not do git tags for releases. In the next release, I plan to start tagging releases.

**Comment by briansmith** [comment]
I filed #250 so everybody can track how this will work going forward. Please comment there if you have ideas about it.
