### ISSUE TITLE
Allow pathLenConstraint on Trust Anchors?

### ISSUE THREAD

**Issue by alex** [briansmith/webpki#58]
Currently the only constraints available are name constraints. What do you think allowing pathLenConstraint as well?

**Comment by briansmith** [comment]
I think path length constraints that aren't "0" are likely trying to solve a problem in a suboptimal way, but zero usually doesn't make sense for a trust anchor, since we usually don't want trust anchors to directly issue end-entity certificates. So I'm skeptical of the potential benefit, without seeing a clear use case.

**Comment by alex** [comment]
I filed this after https://bugs.python.org/issue25115, I personally have no idea what the poster's use case is, but I remembered that webpki didn't expose pathLenConstraint on trust anchors, so I filed this.

**Comment by briansmith** [comment]
OK, I'm just going to close this then. It seems the reporter of the Python bug seems to think the path length constraint works backwards from how it actually works: i.e. he seems to think it's a constraint that the sub-CA imposes on the CA certificates above it, but it actually imposes the constraints on CA certificates below it.
